### PR TITLE
Add ru_ru.json (Russian)

### PR DESCRIPTION
**Pull request by Alexander317**

### CODE REVIEW

**Comment by Nolij** [comment]
recheck

**Comment by Nolij** [comment]
recheck

**Comment by Nolij** [comment]
recheck

**Comment by Nolij** [comment]
Doing this manually since the DCO bot appears to be broken for some reason:

Before we can merge your submission, we require that you read and affirm the contents of the [Developer Certificate of Origin](https://github.com/Nolij/Nolijium/blob/dco/DCO.txt) by adding a comment containing the below text. Otherwise, please close this PR.

"I have read and hereby affirm the entire contents of the Developer Certificate of Origin."

**Comment by Alexander317** [comment]
I have read and hereby affirm the entire contents of the Developer Certificate of Origin.

**Pull request merged**
